# Generated by Django 4.2 on 2024-12-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollutionapp', '0003_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudes', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitudes', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('waterbody', models.TextField()),
                ('watercolour', models.ImageField(upload_to='watercolour/')),
                ('smell', models.TextField()),
                ('odor', models.CharField(max_length=100)),
                ('pollutionform', models.CharField(max_length=100)),
                ('turbidity', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=100)),
                ('nitrates', models.CharField(max_length=100)),
                ('phosphates', models.CharField(max_length=100)),
                ('oxygen', models.CharField(max_length=100)),
                ('algea', models.CharField(max_length=100)),
                ('aquatic', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
