# Generated by Django 4.2 on 2024-12-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollutionapp', '0004_waterdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterdata',
            old_name='latitudes',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='waterdata',
            name='longitudes',
        ),
    ]
