# Generated by Django 4.2 on 2024-12-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollutionapp', '0005_rename_latitudes_waterdata_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterdata',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='waterdata',
            name='image',
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='smell',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='waterbody',
            field=models.CharField(max_length=100),
        ),
    ]
