# Generated by Django 4.2 on 2024-12-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollutionapp', '0007_rename_algea_waterdata_water_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterdata',
            name='algae_blooms',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='aquatic_life',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='odor_description',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='pollution_evidence',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
