# Generated by Django 4.2 on 2024-12-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollutionapp', '0009_alter_donate_amount_alter_donate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
