# Generated by Django 4.2 on 2024-12-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollutionapp', '0010_alter_donate_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
